version: '3'
services:
  site:
    container_name: travel_planner
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_NAME=travel_planner_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "8000:8000"
    networks:
      - db-net
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db-net
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=travel_planner_db

networks:
  db-net:
    driver: bridge
volumes:
  postgres_data:
