name: Build and push container

on:
  push:
    branches: [ "prod" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: athibault18/travel-planner:latest

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -f dockerfile.prod . -t $DOCKER_REGISTRY
      
    - name: Docker Push
      run: docker push $DOCKER_REGISTRY